import type {
  User,
  Donation,
  FoodRequest,
  Delivery,
  Notification,
  DonorStats,
  NgoStats,
  DeliveryStats,
  AdminStats,
} from "@/lib/types";

// Mock Users
export const mockUsers: User[] = [
  {
    id: "1",
    email: "admin@savebite.com",
    name: "System Admin",
    role: "ADMIN",
    phone: "+91 9876543210",
    isVerified: true,
    isApproved: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "2",
    email: "donor@restaurant.com",
    name: "Green Kitchen Restaurant",
    role: "DONOR",
    phone: "+91 9876543211",
    address: "123 Food Street, Andheri West",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400053",
    isVerified: true,
    isApproved: true,
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "3",
    email: "ngo@helpinghands.org",
    name: "Helping Hands Foundation",
    role: "NGO",
    phone: "+91 9876543212",
    address: "456 Charity Lane, Bandra East",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400051",
    isVerified: true,
    isApproved: true,
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: "2024-02-01T00:00:00Z",
  },
  {
    id: "4",
    email: "delivery@partner.com",
    name: "Rajesh Kumar",
    role: "DELIVERY_PARTNER",
    phone: "+91 9876543213",
    city: "Mumbai",
    isVerified: true,
    isApproved: true,
    createdAt: "2024-02-15T00:00:00Z",
    updatedAt: "2024-02-15T00:00:00Z",
  },
  {
    id: "5",
    email: "pending@ngo.org",
    name: "New Hope NGO",
    role: "NGO",
    phone: "+91 9876543214",
    city: "Delhi",
    isVerified: true,
    isApproved: false,
    createdAt: "2024-03-01T00:00:00Z",
    updatedAt: "2024-03-01T00:00:00Z",
  },
];

// Mock Donations
export const mockDonations: Donation[] = [
  {
    id: "d1",
    donorId: "2",
    donorName: "Green Kitchen Restaurant",
    donorPhone: "+91 9876543211",
    title: "Fresh Vegetable Biryani",
    description: "Freshly prepared vegetable biryani with raita. Made with organic vegetables and aromatic basmati rice.",
    foodType: "VEG",
    foodCategory: "COOKED",
    donationType: "FREE",
    quantity: 50,
    unit: "servings",
    servings: 50,
    expiryTime: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    preparedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    images: ["/placeholder.svg?height=300&width=400"],
    pickupAddress: "123 Food Street, Andheri West",
    pickupCity: "Mumbai",
    pickupPincode: "400053",
    pickupInstructions: "Use back entrance, ask for manager",
    status: "AVAILABLE",
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d2",
    donorId: "2",
    donorName: "Green Kitchen Restaurant",
    donorPhone: "+91 9876543211",
    title: "Assorted Sandwiches",
    description: "Variety of fresh sandwiches including paneer tikka, grilled vegetables, and cheese corn.",
    foodType: "VEG",
    foodCategory: "COOKED",
    donationType: "DELIVERY_CHARGE",
    quantity: 30,
    unit: "pieces",
    servings: 30,
    expiryTime: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    images: ["/placeholder.svg?height=300&width=400"],
    pickupAddress: "123 Food Street, Andheri West",
    pickupCity: "Mumbai",
    pickupPincode: "400053",
    deliveryCharge: 100,
    status: "REQUESTED",
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d3",
    donorId: "2",
    donorName: "Green Kitchen Restaurant",
    donorPhone: "+91 9876543211",
    title: "Fresh Fruits Basket",
    description: "Assorted seasonal fruits including apples, bananas, oranges, and grapes.",
    foodType: "VEGAN",
    foodCategory: "FRUITS_VEGETABLES",
    donationType: "DISCOUNT",
    quantity: 20,
    unit: "kg",
    expiryTime: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
    images: ["/placeholder.svg?height=300&width=400"],
    pickupAddress: "123 Food Street, Andheri West",
    pickupCity: "Mumbai",
    pickupPincode: "400053",
    originalPrice: 1000,
    discountPrice: 400,
    status: "AVAILABLE",
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d4",
    donorId: "2",
    donorName: "Green Kitchen Restaurant",
    donorPhone: "+91 9876543211",
    title: "Chicken Curry with Rice",
    description: "Home-style chicken curry with steamed rice. Mildly spiced, suitable for all age groups.",
    foodType: "NON_VEG",
    foodCategory: "COOKED",
    donationType: "EMERGENCY",
    quantity: 25,
    unit: "servings",
    servings: 25,
    expiryTime: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    preparedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    images: ["/placeholder.svg?height=300&width=400"],
    pickupAddress: "123 Food Street, Andheri West",
    pickupCity: "Mumbai",
    pickupPincode: "400053",
    status: "AVAILABLE",
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: "d5",
    donorId: "2",
    donorName: "Green Kitchen Restaurant",
    donorPhone: "+91 9876543211",
    title: "Packaged Snacks",
    description: "Assorted packaged snacks including chips, biscuits, and namkeen.",
    foodType: "VEG",
    foodCategory: "PACKAGED",
    donationType: "FREE",
    quantity: 100,
    unit: "packets",
    expiryTime: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    images: ["/placeholder.svg?height=300&width=400"],
    pickupAddress: "123 Food Street, Andheri West",
    pickupCity: "Mumbai",
    pickupPincode: "400053",
    status: "DELIVERED",
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// Mock Food Requests
export const mockRequests: FoodRequest[] = [
  {
    id: "r1",
    donationId: "d2",
    ngoId: "3",
    ngoName: "Helping Hands Foundation",
    ngoPhone: "+91 9876543212",
    pickupType: "DELIVERY_REQUIRED",
    requestedQuantity: 30,
    message: "We serve 50 children daily at our shelter. This would be a great help!",
    status: "PENDING",
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "r2",
    donationId: "d5",
    ngoId: "3",
    ngoName: "Helping Hands Foundation",
    ngoPhone: "+91 9876543212",
    pickupType: "SELF_PICKUP",
    requestedQuantity: 100,
    status: "APPROVED",
    deliveryId: "del1",
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// Mock Deliveries
export const mockDeliveries: Delivery[] = [
  {
    id: "del1",
    requestId: "r2",
    deliveryPartnerId: "4",
    deliveryPartnerName: "Rajesh Kumar",
    deliveryPartnerPhone: "+91 9876543213",
    pickupAddress: "123 Food Street, Andheri West, Mumbai - 400053",
    deliveryAddress: "456 Charity Lane, Bandra East, Mumbai - 400051",
    status: "DELIVERED",
    verification: {
      foodFresh: true,
      quantityMatches: true,
      imageMatches: true,
      safePackaging: true,
      notes: "All items verified and in good condition",
    },
    pickupTime: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    deliveryTime: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    distance: 8.5,
    estimatedTime: 25,
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "del2",
    requestId: "r1",
    deliveryPartnerId: "4",
    deliveryPartnerName: "Rajesh Kumar",
    deliveryPartnerPhone: "+91 9876543213",
    pickupAddress: "123 Food Street, Andheri West, Mumbai - 400053",
    deliveryAddress: "456 Charity Lane, Bandra East, Mumbai - 400051",
    status: "ASSIGNED",
    distance: 8.5,
    estimatedTime: 25,
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
];

// Mock Notifications
export const mockNotifications: Notification[] = [
  {
    id: "n1",
    userId: "2",
    title: "New Request",
    message: "Helping Hands Foundation requested your Assorted Sandwiches donation",
    type: "INFO",
    isRead: false,
    link: "/donor/donations",
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "n2",
    userId: "3",
    title: "Delivery Assigned",
    message: "Your request for Packaged Snacks has been assigned to a delivery partner",
    type: "SUCCESS",
    isRead: true,
    link: "/ngo/track",
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "n3",
    userId: "4",
    title: "New Delivery Task",
    message: "You have been assigned a new delivery task",
    type: "INFO",
    isRead: false,
    link: "/delivery/tasks",
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
];

// Mock Stats
export const mockDonorStats: DonorStats = {
  totalDonations: 45,
  activeDonations: 4,
  completedDonations: 38,
  totalQuantityDonated: 1250,
  impactScore: 92,
  mealsProvided: 2500,
};

export const mockNgoStats: NgoStats = {
  totalRequests: 78,
  pendingRequests: 3,
  completedRequests: 72,
  totalFoodReceived: 850,
  beneficiariesServed: 1500,
};

export const mockDeliveryStats: DeliveryStats = {
  totalDeliveries: 156,
  activeDeliveries: 2,
  completedDeliveries: 150,
  averageRating: 4.8,
  distanceCovered: 1250,
};

export const mockAdminStats: AdminStats = {
  totalUsers: 1250,
  totalDonors: 450,
  totalNgos: 120,
  totalDeliveryPartners: 80,
  pendingApprovals: 15,
  totalDonations: 3500,
  activeDonations: 125,
  completedDeliveries: 2800,
  foodSaved: 25000,
  mealsProvided: 75000,
};

// Helper function to get current user (simulated)
export const getCurrentUser = (): User | null => {
  // In real app, this would check localStorage/cookies for JWT
  return mockUsers[1]; // Return donor by default for demo
};

// Chart data for analytics
export const donationTrendData = [
  { month: "Jan", donations: 45, delivered: 42 },
  { month: "Feb", donations: 52, delivered: 48 },
  { month: "Mar", donations: 61, delivered: 55 },
  { month: "Apr", donations: 58, delivered: 54 },
  { month: "May", donations: 72, delivered: 68 },
  { month: "Jun", donations: 85, delivered: 80 },
];

export const foodCategoryData = [
  { name: "Cooked Food", value: 45, fill: "var(--chart-1)" },
  { name: "Packaged", value: 25, fill: "var(--chart-2)" },
  { name: "Fruits & Veg", value: 15, fill: "var(--chart-3)" },
  { name: "Bakery", value: 10, fill: "var(--chart-4)" },
  { name: "Others", value: 5, fill: "var(--chart-5)" },
];

export const weeklyDeliveryData = [
  { day: "Mon", deliveries: 12 },
  { day: "Tue", deliveries: 18 },
  { day: "Wed", deliveries: 15 },
  { day: "Thu", deliveries: 22 },
  { day: "Fri", deliveries: 28 },
  { day: "Sat", deliveries: 35 },
  { day: "Sun", deliveries: 20 },
];
